swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Ui Vulnerable to Html Injection 
  description: <img src=x onerror=alert('XSS')>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful